//
//  ServicoDeSpoiler.swift
//  ProjetoIntegrador
//
//  Created by Gui  on 23/06/22.
//

import Foundation

class ServicoDeSpoiler {
    
    var listaDeFilmesSpoiler: [Spoiler] = [
    
        Spoiler(title: "Ant-Man and The Wasp: Quantumania", spoiler: "Homem-Formiga e a Vespa vê o retorno dos menores heróis da Marvel Studios - Scott Lang aka. Homem-Formiga (Paul Rudd)e Hope van Dyne, também conhecido como. Wasp (Evangeline Lilly)– então quais foram os maiores spoilers, reviravoltas e surpresas nasequência do Homem-Formiga ? Nós os quebramos. Homem-Formiga e a Vespa começa dois anos após os eventos de Capitão América: Guerra Civil , que viu Scott violar os Acordos de Sokovia da ONU para ajudar Steve Rogers. Como resultado, ele foi preso, mas fez um acordo com o FBI para ficar em prisão domiciliar, que está chegando ao fim. No entanto, seus associados, Hank Pym (Michael Douglas) e Hope, estão fugindo há dois anos. Quando Scott se reconecta com eles, ele descobre que eles estão construindo um Túnel Quântico na tentativa de resgatar Janet van Dyne (Michelle Pfeiffer) do Reino Quântico. Infelizmente, existem obstáculos para Hank e Hope chegarem ao Reino Quântico, incluindo um novo inimigo misterioso que eles chamam de Fantasma (Hannah John-Kamen).", elenco: "Paul Rudd, Evangeline Lilly, Michael Douglas, Michelle Pfeiffer, Kathryn Newton, Jonathan Majors", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Guardians of the Galaxy Vol. 3", spoiler: nil, elenco: "Chris Pratt, Zoë Saldaña, Dave Bautista, Vin Diesel, Bradley Cooper, Karen Gillan, Pom Klementieff, Sean Gunn, Sylvester Stallone, Will Poulter", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Fantastic Four", spoiler: nil, elenco: "Ioan Gruffudd, Jessica Alba, Michael Chiklis, Chris Evans, Julian McMahon, Laurie Holden", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Black Panther: Wakanda Forever", spoiler: "A primeira cena: Acompanhado por Nakia (Lupita Nyong'o), Okoye (Danai Gurira) e Ayo (Florence Kasumba), o rei T'Challa (Chadwick Boseman) faz um discurso na sede da ONU em um momento que havia sido vislumbrado nos trailers. A segunda cena: Em uma tenda, três crianças observam e brincam com alguma coisa. Bucky Barnes deixa o local, ainda sem o braço mecânico (perdido em Guerra Civil). Ele encontra Shuri, que pergunta: “Como se sente Sargento Barnes?”. Ele pede para ser chamado de Bucky, dando a entender que está completamente recuperado da lavagem cerebral sofrida no passado. “Venha, há muitas coisas que você precisa entender”, diz a princesa.", elenco: "Lupita Nyong'o, Danai Gurira, Martin Freeman, Daniel Kaluuya, Letitia Wright, Winston Duke, Angela Bassett, Dominique Thorne", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Blade", spoiler: nil, elenco: "ainda não tem lista de elenco", descricaoCenaPosCreditos: nil),
        Spoiler(title: "The Marvels", spoiler: "Homem aranha morre", elenco: "Brie Larson, Teyonah Parris, Iman Vellani, Samuel L. Jackson", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Thor: Love and Thunder", spoiler: nil, elenco: "Chris Hemsworth, Christian Bale, Tessa Thompson, Jaimie Alexander, Taika Waititi, Russell Crowe, Natalie Portman", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Doctor Strange in the Multiverse of Madness", spoiler: "", elenco: "Benedict Cumberbatch, Elizabeth Olsen, Chiwetel Ejiofor, Benedict Wong, Xochitl Gomez, Michael Stuhlbarg, Rachel McAdams", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Spider-Man: No Way Home", spoiler: "", elenco: "Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon, Jon Favreau, Jamie Foxx, Willem Dafoe, Alfred Molina, Benedict Wong, Tony Revolori, Marisa Tomei, Andrew Garfield, Tobey Maguire", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Eternals", spoiler: "", elenco: "Gemma Chan, Richard Madden, Kumail Nanjiani, Lia McHugh, Brian Tyree Henry, Lauren Ridloff, Barry Keoghan, Don Lee, Harish Patel, Kit Harington, Salma Hayek, Angelina Jolie", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Shang-Chi and The Legend of The Ten Rings", spoiler: "", elenco: "Simu Liu, Awkwafina, Meng'er Zhang, Fala Chen, Florian Munteanu, Benedict Wong, Michelle Yeoh, Ben Kingsley, Tony Leung", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Spider-Man: Far From Home", spoiler: "", elenco: "Tom Holland, Samuel L. Jackson, Zendaya, Cobie Smulders, Jon Favreau, J. B. Smoove, Jacob Batalon, Martin Starr, Marisa Tomei, Jake Gyllenhaal", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Avengers: Endgame", spoiler: "", elenco: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Brie Larson, Karen Gillan, Danai Gurira, Benedict Wong, Jon Favreau, Bradley Cooper, Gwyneth Paltrow, Josh Brolin", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Avengers: Infinity War", spoiler: "", elenco: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans, Scarlett Johansson, Benedict Cumberbatch, Don Cheadle, Tom Holland, Chadwick Boseman, Paul Bettany, Elizabeth Olsen, Anthony Mackie, Sebastian Stan, Danai Gurira, Letitia Wright, Dave Bautista, Zoe Saldaña, Josh Brolin, Chris Pratt", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Ant-Man and The Wasp", spoiler: "", elenco: "Paul Rudd, Evangeline Lilly, Michael Peña, Walton Goggins, Bobby Cannavale, Judy Greer, Tip T.I. Harris, David Dastmalchian, Hannah John-Kamen, Abby Ryder Fortson, Randall Park, Michelle Pfeiffer, Laurence Fishburne, Michael Douglas", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Thor: Ragnarok", spoiler: "", elenco: "Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Idris Elba, Tessa Thompson, Jeff Goldblum, Karl Urban, Mark Ruffalo, Anthony Hopkins, Matt Damon", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Doctor Strange", spoiler: "", elenco: "Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Benedict Wong, Michael Stuhlbarg, Benjamin Bratt, Mads Mikkelsen, Tilda Swinton", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Black Panther", spoiler: "", elenco: "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Letitia Wright, Martin Freeman, Daniel Kaluuya, Angela Bassett, Winston Duke, Danai Gurira, Andy Serkis, Forest Whitaker", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Spider-Man: Homecoming", spoiler: "", elenco: "Tom Holland, Michael Keaton, Jon Favreau, Zendaya, Donald Glover, Jacob Batalon, Laura Harrier, Tony Revolori, Bokeem Woodbine, Tyne Daly, Marisa Tomei, Robert Downey Jr.", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Black Widow", spoiler: "", elenco: "Scarlett Johansson, Florence Pugh, David Harbour, O-T Fagbenle, Olga Kurylenko, William Hurt, Ray Winstone, Rachel Weisz", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Captain America: Civil War", spoiler: "", elenco: "Chris Evans, Robert Downey Jr., Scarlett Johansson, Sebastian Stan, Daniel Brühl, Chadwick Boseman, Elizabeth Olsen, Emily VanCamp, Don Cheadle, Paul Bettany, Jeremy Renner, Anthony Mackie, Paul Rudd, William Hurt, Martin Freeman, Tom Holland, Frank Grillo, Marisa Tomei", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Ant-Man", spoiler: "", elenco: "Paul Rudd, Evangeline Lilly, Corey Stoll, Bobby Cannavale, Michael Peña, Tip T.I. Harris, Anthony Mackie, Wood Harris, Judy Greer, David Dastmalchian, Michael Douglas", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Avengers: Age of Ultron", spoiler: "", elenco: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans, Scarlett Johansson, Jeremy Renner, James Spader, Don Cheadle, Aaron Taylor-Johnson, Elizabeth Olsen, Paul Bettany, Cobie Smulders, Anthony Mackie, Hayley Atwell, Idris Elba, Stellan Skarsgård, Linda Cardellini, Thomas Kretschmann, Claudia Kim, Andy Serkis, Samuel L. Jackson", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Guardians of the Galaxy Vol. 2", spoiler: "", elenco: "Chris Pratt, Zoe Saldaña, Dave Bautista, Vin Diesel, Bradley Cooper, Michael Rooker, Karen Gillan, Pom Klementieff, Elizabeth Debicki, Chris Sullivan, Sean Gunn, Sylvester Stallone, Kurt Russell", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Guardians of the Galaxy", spoiler: "", elenco: "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel, Bradley Cooper, Lee Pace, Michael Rooker, Karen Gillan, Djimon Hounsou, John C. Reilly, Glenn Close, Benicio Del Toro", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Captain America: The Winter Soldier", spoiler: "", elenco: "Chris Evans, Scarlett Johansson, Sebastian Stan, Anthony Mackie, Cobie Smulders, Frank Grillo, Emily VanCamp, Hayley Atwell, Robert Redford, Samuel L. Jackson", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Thor: The Dark World", spoiler: "", elenco: "Chris Hemsworth, Natalie Portman, Tom Hiddleston, Anthony Hopkins, Stellan Skarsgård, Idris Elba, Christopher Eccleston, Adewale Akinnuoye-Agbaje, Kat Dennings, Ray Stevenson, Zachary Levi, Tadanobu Asano, Jaimie Alexander, Rene Russo", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Iron Man 3", spoiler: "", elenco: "Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Guy Pearce, Rebecca Hall, Stéphanie Szostak, James Badge Dale, Jon Favreau, Ben Kingsley", descricaoCenaPosCreditos: nil),
        Spoiler(title: "The Avengers", spoiler: "", elenco: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Tom Hiddleston, Clark Gregg, Cobie Smulders, Stellan Skarsgård, Samuel L. Jackson", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Thor", spoiler: "", elenco: "Chris Hemsworth, Natalie Portman, Tom Hiddleston, Stellan Skarsgård, Colm Feore, Ray Stevenson, Idris Elba, Kat Dennings, Rene Russo, Anthony Hopkins", descricaoCenaPosCreditos: nil),
        Spoiler(title: "The Incredible Hulk", spoiler: "", elenco: "Edward Norton, Liv Tyler, Tim Roth, William Hurt, Tim Blake Nelson, Ty Burrell", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Iron Man 2", spoiler: "", elenco: "Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Scarlett Johansson, Sam Rockwell, Mickey Rourke, Samuel L. Jackson", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Iron Man", spoiler: "", elenco: "Robert Downey Jr., Terrence Howard, Jeff Bridges, Shaun Toub, Gwyneth Paltrow", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Captain Marvel", spoiler: "", elenco: "Brie Larson, Samuel L. Jackson, Ben Mendelsohn, Djimon Hounsou, Lee Pace, Lashana Lynch, Gemma Chan, Annette Bening, Clark Gregg, Jude Law", descricaoCenaPosCreditos: nil),
        Spoiler(title: "Captain America: The First Avenger", spoiler: "", elenco: "Chris Evans, Tommy Lee Jones, Hugo Weaving, Hayley Atwell, Sebastian Stan, Dominic Cooper, Neal McDonough, Derek Luke, Stanley Tucci", descricaoCenaPosCreditos: nil)
        
    ]
    
}
